services:  
  mysql:
    container_name: sample-mysql
    image: mysql:8.0.44
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sample_db
      - MYSQL_USER=sample_user
      - MYSQL_PASSWORD=123456
    ports:
      - "3307:3306"  
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql